name: Deploy

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: configure Buildx
        run: docker buildx create --use
      - name: Deploy Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64/v8 \
            -t "flyingjoe/gdal-python:3.8-ubuntu" 3.8-ubuntu/ \
            -f 3.8-ubuntu/Dockerfile \
            --push